# config.py
# 页面配置
from pathlib import Path

api = {"key":
"f7bd69fb1e124bb79560a0e726fb4631",
'end':'https://hkust.azure-api.net/openai/deployments/{deployment-id}/chat/completions?api-version=2024-10-21',}

APP_CONFIG = {
    "page_layout": "wide",
    "logo_path": "images/starteam-logo.png",
    "logo_size": "Large",
    "pages": {
        "faq": {"title": "FAQ - STARTEAM Global"},
        "eq_search": {"title": "EQ Searching Page"},
        "create_eq": {"title": "Create EQ - STARTEAM Global"},
        "translator": {"title": "Create EQ - Translator"},
        "dashboard": {"title": "EQ Management Dashboard"}
    }
}

# 状态图标
STATUS_ICONS = {
    "Closed": "✅",
    "Pending": "🔄",
    "Reviewing": "⏳"
}

# 语言配置
LANGUAGES = {
    "zh-CN": "简体中文",
    "zh-TW": "繁體中文",
    "de": "Deutsch",
    "en": "English"
}

# 国际化消息
MESSAGES = {
    "zh-CN": {"questionPrefix": "问题：",
            "Create_eq_title": "创建EQ界面",
        
        "No Description": "无描述",
        "manage_eq_title": "EQ文件管理界面",
        "unknown": "未知",
        "similarityLabel": "相似度：{similarity}%",
        "noReply": "无回复",
        "replyImageCaption": "回复图片",
        "csvFileNotFound": "CSV 文件 {file} 不存在",
        "csvReadError": "无法读取 CSV 文件 {file}：{error}",
        "csvUtf8Warning": "UTF-8 编码失败，尝试使用 latin1 编码读取 {file}",
        "csvEmptyWarning": "CSV 文件 {file} 为空",
        "imageNotFoundWarning": "行 {row} 的图片 {image} 不存在于 {dir}",
        "rowProcessingError": "处理行 {row} 时出错，跳过该行：{error}",
        "csvNoDataWarning": "CSV 文件 {file} 未生成任何有效数据",
        "csvLoadSuccess": "成功从 {file} 加载 {count} 条记录",
        "searchKeyword": "搜索客户名称、客户 P/N...",
        "searchItemCode": "搜索项目代码/STG P/N...",
        "allStatus": "所有状态",
        "allFactories": "所有工厂",
        "engineerTeam": "工程师团队",
        "engineerName": "工程师姓名",
        "csName": "客服姓名",
        "noDataFound": "未找到数据",
        "previous": "上一页",
        "next": "下一页",
        "page": "页",
        "of": "共",
        "perPage": "每页",
        "backToDashboard": "返回仪表板",
        "selectAll": "全选",
        "image": "图片",
        "translateText": "翻译文本",
        "translateDocument": "翻译文档",
        "translateImage": "翻译图片",
        "translateWeb": "翻译网页",
        "sourceLang": "源语言",
        "targetLang": "目标语言",
        "swapLang": "交换语言",
        "inputText": "输入要翻译的文本...",
        "uploadDocument": "上传文档（.docx、.pdf、.txt）",
        "uploadImage": "上传图片（.jpg、.png）",
        "inputUrl": "输入网页 URL",
        "noTextExtracted": "未提取到文本",
        "translationFailed": "翻译失败",
        "usageInstructions": """
            **使用说明：**
            - 选择源语言和目标语言（或选择“自动检测”源语言）。
            - 在相应标签页中输入文本、上传文档、上传图片或输入网页 URL。
            - 点击相应的“翻译”按钮查看翻译结果。
            - 使用 🔄 按钮交换语言。
        """,
        "languageSelect": "选择语言",
        "createNewCase": "创建新案例",
        "editEQ": "编辑 EQ",
        "exportEQ": "导出 EQ",
        "eqInformation": "EQ 信息",
        "questionDescription": "问题描述",
        "uploadImage": "上传相关图片",
        "finalDescription": "最终描述",
        "engineerSuggestion": "工程师建议",
        "attachments": "附件",
        "save": "保存",
        "delete": "删除",
        "addQuestion": "添加问题",
        "exportAndSend": "导出并发送",
        "pendingIssues": "待解决问题",
        "statusTracking": "问题状态追踪",
        "recentQuestions": "最新问题展示",
        "viewDetails": "查看完整详情",
        "faq_title": "EQ问题管理界面",
        "eq_search_title": "EQ 搜索页面",
        "create_eq_title": "创建EQ界面",
        "translator_title": "翻译器",
        "dashboard_title": "主界面",
        "eqOverview": "EQs情况总览",
        "unresolvedEQs": "未解决的EQs(按日期分类)",
        "unresolvedDescription": "未解决的EQs：状态为Reviewing和Pending的EQs。<br>天数=系统日期-EQ创建日期",
        "over7Days": "超过7天",
        "between2to7Days": "2至7天内",
        "under2Days": "少于2天",
        "viewDetails": "查看详情",
        "navigateToEQManage": "导航到EQ管理页面，筛选条件：{filter}",
        "filterOver7": "超过7天",
        "filterBetween2to7": "2至7天内",
        "filterUnder2": "少于2天","filterByCustomer": "按客户筛选",
        "selectCustomer": "选择客户",
        "allCustomers": "所有客户",
        "allStatuses": "所有状态",
        "keyword": "关键词",
        "startDate": "开始日期",
        "endDate": "结束日期",
        "status": "状态",
        "stgPN": "STG P/N",
        "itemsPerPage": "每页显示条数",
        "faqTime": "时间：",
        "faqCustomer": "客户：",
        "faqStatus": "状态：",
        "faqStgPN": "STG P/N：",
        "faqEngineer": "工程师：",
        "faqCustomerReply": "客户回复：",
        "previousPage": "上一页",
        "nextPage": "下一页",
        "pageInfo": "第 {current_page} 页 / 共 {total_pages} 页 (总计 {total_items} 条)",
        "loadFaqError": "加载 FAQ 数据失败：{error}","translatorHeader": "翻译器",
        "tabText": "文本",
        "tabDocument": "文档",
        "tabImage": "图片",
        "tabWeb": "网页",
        "translating": "正在翻译...",
        "enterTextWarning": "请输入要翻译的文本。",
        "unsupportedFileType": "不支持的文件类型。",
        "translationResult": "翻译结果：",
        "extractedText": "提取的文本：","searchEQHeader": "搜索 EQ",
        "keywordSearch": "关键词检索",
        "customerName": "客户名称",
        "invalidDateRangeError": "开始日期不能晚于结束日期",
        "dateFilterError": "日期筛选错误：{error}",
        "filterError": "筛选失败：{error}",
        "eqNotFoundError": "未找到对应 EQ 数据！",
        "singleEQEditError": "请仅选择一个 EQ 进行编辑。",
        "exportingEQs": "正在导出 {count} 个 EQ...",
        "downloadCSV": "下载 CSV",
        "exportedEQsFile": "exported_eqs.csv",
        "selectEQExportError": "请至少选择一个 EQ 进行导出。",
        "exportSuccess": "{count} 个 EQ 已导出！",
        "selectColumn": "选择",
        "idColumn": "ID",
        "eqStatusColumn": "EQ 状态",
        "closeDateColumn": "关闭日期",
        "customerColumn": "客户",
        "customerPNColumn": "客户 P/N",
        "factoryPNColumn": "工厂 P/N",
        "engineerColumn": "工程师",
        "stgPNColumn": "STG P/N",
        "baseMaterialColumn": "基材",
        "solderMaskColumn": "阻焊",
        "filePathColumn": "文件路径",
        "pluggingColumn": "塞孔类型","eqList": "EQ 列表",
        "addEQ": "添加 EQ",
        "NewQ":"新问题",
        "exportExcel": "导出为 Excel",
        "searchButton": "搜索",
        "questionLabel": "问题",
        "searching": "正在搜索...",
        "eqInformationHeader": "EQ 信息",
        "customerNamePlaceholder": "请输入客户名称，例如：ABC Company",
        "stgPNPlaceholder": "请输入 STG 零件号，例如：STG12345",
        "factoryEngineer": "工厂工程师",
        "factoryEngineerPlaceholder": "请输入工厂工程师姓名，例如：张伟",
        "baseMaterialPlaceholder": "请输入基材类型，例如：FR4",
        "customerPNPlaceholder": "请输入客户零件号，例如：CUST67890",
        "factoryPNPlaceholder": "请输入工厂零件号，例如：FACT45678",
        "panelSize": "尺寸 (mm*mm)",
        "panelSizePlaceholder": "请输入交货板尺寸，例如：500*600 mm",
        "solderMaskPlaceholder": "请输入阻焊层信息，例如：绿色光泽",
        "viaPluggingType": "塞孔类型",
        "viaPluggingTypePlaceholder": "请输入塞孔类型",
        "issueDate": "日期",
        "descriptionLabel": "描述",
        "uploadImageLabel": "上传图片（不支持 Gerber 文件）",
        "uploadedImageCaption": "已上传图片",
        "aiWriter": "AI 写作",
        "finalDescriptionLabel": "最终描述",
        "engineerSuggestionLabel": "工程师建议",
        "attachmentLabel": "附件",
        "reviewingStatus": "审核中",
        "pendingStatus": "待处理",
        "closedStatus": "已关闭",
        "missingFieldsError": "请填写所有必填字段。",
        "noQuestionsError": "请至少添加一个问题。",
        "exportingAndSending": "正在导出并发送...",
        "exportReviewingSuccess": "EQ 已导出并发送！",
        "exportPendingSuccess": "待处理问题已导出！",
        "exportClosedSuccess": "客户回复已保存！","eqList": "EQ 列表",
        "addEQ": "添加 EQ",
        "exportExcel": "导出为 Excel",
        "searchButton": "搜索",
        "questionLabel": "问题",
        "searching": "正在搜索...",
        "eqInformationHeader": "EQ 信息",
        "customerNamePlaceholder": "请输入客户名称，例如：ABC Company",
        "stgPNPlaceholder": "请输入 STG 零件号，例如：STG12345",
        "factoryEngineer": "工厂工程师",
        "factoryEngineerPlaceholder": "请输入工厂工程师姓名，例如：张伟",
        "baseMaterialPlaceholder": "请输入基材类型，例如：FR4",
        "customerPNPlaceholder": "请输入客户零件号，例如：CUST67890",
        "factoryPNPlaceholder": "请输入工厂零件号，例如：FACT45678",
        "panelSize": "尺寸 (mm*mm)",
        "panelSizePlaceholder": "请输入交货板尺寸，例如：500*600 mm",
        "solderMaskPlaceholder": "请输入阻焊层信息，例如：绿色光泽",
        "viaPluggingType": "塞孔类型",
        "viaPluggingTypePlaceholder": "请输入塞孔类型",
        "issueDate": "日期",
        "descriptionLabel": "描述",
        "uploadImageLabel": "上传图片（不支持 Gerber 文件）",
        "uploadedImageCaption": "已上传图片",
        "aiWriter": "AI 写作",
        "finalDescriptionLabel": "最终描述",
        "engineerSuggestionLabel": "工程师建议",
        "attachmentLabel": "附件",
        "reviewingStatus": "审核中",
        "pendingStatus": "待处理",
        "closedStatus": "已关闭",
        "missingFieldsError": "请填写所有必填字段。",
        "noQuestionsError": "请至少添加一个问题。",
        "exportingAndSending": "正在导出并发送...",
        "exportReviewingSuccess": "EQ 已导出并发送！",
        "exportPendingSuccess": "待处理问题已导出！",
        "exportClosedSuccess": "客户回复已保存！",
        "Setting":"设置",
    },
    "zh-TW": {"questionPrefix": "問題：",
              "Create_eq_title": "建立EQ介面",
        "manage_eq_title": "EQ管理介面",
        "No Description": "无描述",
        "unknown": "未知",
        "similarityLabel": "相似度：{similarity}%",
        "noReply": "無回覆",
        "replyImageCaption": "回覆圖片",
        "csvFileNotFound": "CSV 文件 {file} 不存在",
        "csvReadError": "無法讀取 CSV 文件 {file}：{error}",
        "csvUtf8Warning": "UTF-8 編碼失敗，嘗試使用 latin1 編碼讀取 {file}",
        "csvEmptyWarning": "CSV 文件 {file} 為空",
        "imageNotFoundWarning": "行 {row} 的圖片 {image} 不存在於 {dir}",
        "rowProcessingError": "處理行 {row} 時出錯，跳過該行：{error}",
        "csvNoDataWarning": "CSV 文件 {file} 未生成任何有效數據",
        "csvLoadSuccess": "成功從 {file} 加載 {count} 條記錄",
        "eqList": "EQ 清單",
        "addEQ": "添加 EQ",
        "exportExcel": "導出為 Excel",
        "searchButton": "搜尋",
        "questionLabel": "問題",
        "searching": "正在搜尋...",
        "eqInformationHeader": "EQ 資訊",
        "customerNamePlaceholder": "請輸入客戶名稱，例如：ABC Company",
        "stgPNPlaceholder": "請輸入 STG 零件號，例如：STG12345",
        "factoryEngineer": "工廠工程師",
        "factoryEngineerPlaceholder": "請輸入工廠工程師姓名，例如：張偉",
        "baseMaterialPlaceholder": "請輸入基材類型，例如：FR4",
        "customerPNPlaceholder": "請輸入客戶零件號，例如：CUST67890",
        "factoryPNPlaceholder": "請輸入工廠零件號，例如：FACT45678",
        "panelSize": "尺寸 (mm*mm)",
        "panelSizePlaceholder": "請輸入交貨板尺寸，例如：500*600 mm",
        "solderMaskPlaceholder": "請輸入阻焊層資訊，例如：綠色光澤",
        "viaPluggingType": "塞孔類型",
        "viaPluggingTypePlaceholder": "請輸入塞孔類型",
        "issueDate": "日期",
        "descriptionLabel": "描述",
        "uploadImageLabel": "上傳圖片（不支持 Gerber 文件）",
        "uploadedImageCaption": "已上傳圖片",
        "aiWriter": "AI 寫作",
        "finalDescriptionLabel": "最終描述",
        "engineerSuggestionLabel": "工程師建議",
        "attachmentLabel": "附件",
        "reviewingStatus": "審核中",
        "pendingStatus": "待處理",
        "closedStatus": "已關閉",
        "missingFieldsError": "請填寫所有必填欄位。",
        "noQuestionsError": "請至少添加一個問題。",
        "exportingAndSending": "正在導出並發送...",
        "exportReviewingSuccess": "EQ 已導出並發送！",
        "exportPendingSuccess": "待處理問題已導出！",
        "exportClosedSuccess": "客戶回覆已保存！",
        "searchKeyword": "搜尋客戶名稱、客戶 P/N...",
        "searchItemCode": "搜尋項目代碼/STG P/N...",
        "allStatus": "所有狀態",
        "allFactories": "所有工廠",
        "engineerTeam": "工程師團隊",
        "engineerName": "工程師姓名",
        "csName": "客服姓名",
        "noDataFound": "未找到資料",
        "previous": "上一頁",
        "next": "下一頁",
        "page": "頁",
        "of": "共",
        "perPage": "每頁",
        "backToDashboard": "返回儀表板",
        "selectAll": "全選",
        "image": "圖片",
        "translateText": "翻譯文本",
        "translateDocument": "翻譯文件",
        "translateImage": "翻譯圖片",
        "translateWeb": "翻譯網頁",
        "sourceLang": "源語言",
        "targetLang": "目標語言",
        "swapLang": "交換語言",
        "inputText": "輸入要翻譯的文本...",
        "uploadDocument": "上傳文件（.docx、.pdf、.txt）",
        "uploadImage": "上傳圖片（.jpg、.png）",
        "inputUrl": "輸入網頁 URL",
        "noTextExtracted": "未提取到文本",
        "translationFailed": "翻譯失敗",
        "usageInstructions": """
            **使用說明：**
            - 選擇源語言和目標語言（或選擇“自動檢測”源語言）。
            - 在相應標籤頁中輸入文本、上傳文件、上傳圖片或輸入網頁 URL。
            - 點擊相應的“翻譯”按鈕查看翻譯結果。
            - 使用 🔄 按鈕交換語言。
        """,
        "languageSelect": "選擇語言",
        "createNewCase": "創建新案例",
        "editEQ": "編輯 EQ",
        "exportEQ": "導出 EQ",
        "eqInformation": "EQ 資訊",
        "questionDescription": "問題描述",
        "uploadImage": "上傳相關圖片",
        "finalDescription": "最終描述",
        "engineerSuggestion": "工程師建議",
        "attachments": "附件",
        "save": "儲存",
        "delete": "刪除",
        "addQuestion": "新增問題",
        "exportAndSend": "導出並發送",
        "pendingIssues": "待解決問題",
        "statusTracking": "問題狀態追蹤",
        "recentQuestions": "最新問題展示",
        "viewDetails": "查看完整詳情",
        "faq_title": "EQ問題管理器",
        "eq_search_title": "EQ 搜尋頁面",
        "create_eq_title": "建立EQ介面",
        "translator_title": "翻譯器",
        "dashboard_title": "主介面","eqOverview": "EQs情況總覽",
        "unresolvedEQs": "未解決的EQs(按日期分類)",
        "unresolvedDescription": "未解決的EQs：狀態為Reviewing和Pending的EQs。<br>天數=系統日期-EQ創建日期",
        "over7Days": "超過7天",
        "between2to7Days": "2至7天內",
        "under2Days": "少於2天",
        "viewDetails": "查看詳情",
        "navigateToEQManage": "導航到EQ管理頁面，篩選條件：{filter}",
        "filterOver7": "超過7天",
        "filterBetween2to7": "2至7天內",
        "filterUnder2": "少於2天","filterByCustomer": "按客戶篩選",
        "selectCustomer": "選擇客戶",
        "allCustomers": "所有客戶",
        "allStatuses": "所有狀態",
        "keyword": "關鍵詞",
        "startDate": "開始日期",
        "endDate": "結束日期",
        "status": "狀態",
        "stgPN": "STG P/N",
        "itemsPerPage": "每頁顯示條數",
        "faqTime": "時間：",
        "faqCustomer": "客戶：",
        "faqStatus": "狀態：",
        "faqStgPN": "STG P/N：",
        "faqEngineer": "工程師：",
        "faqCustomerReply": "客戶回覆：",
        "previousPage": "上一頁",
        "nextPage": "下一頁",
        "pageInfo": "第 {current_page} 頁 / 共 {total_pages} 頁 (總計 {total_items} 條)",
        "loadFaqError": "加載 FAQ 數據失敗：{error}",
        "translatorHeader": "翻譯器",
        "tabText": "文本",
        "tabDocument": "文件",
        "tabImage": "圖片",
        "tabWeb": "網頁",
        "translating": "正在翻譯...",
        "enterTextWarning": "請輸入要翻譯的文本。",
        "unsupportedFileType": "不支持的文件類型。",
        "translationResult": "翻譯結果：",
        "extractedText": "提取的文本：","searchEQHeader": "搜尋 EQ",
        "keywordSearch": "關鍵詞檢索",
        "customerName": "客戶名稱",
        "invalidDateRangeError": "開始日期不能晚於結束日期",
        "dateFilterError": "日期篩選錯誤：{error}",
        "filterError": "篩選失敗：{error}",
        "eqNotFoundError": "未找到對應 EQ 數據！",
        "singleEQEditError": "請僅選擇一個 EQ 進行編輯。",
        "exportingEQs": "正在導出 {count} 個 EQ...",
        "downloadCSV": "下載 CSV",
        "exportedEQsFile": "exported_eqs.csv",
        "selectEQExportError": "請至少選擇一個 EQ 進行導出。",
        "exportSuccess": "{count} 個 EQ 已導出！",
        "selectColumn": "選擇",
        "idColumn": "ID",
        "eqStatusColumn": "EQ 狀態",
        "closeDateColumn": "關閉日期",
        "customerColumn": "客戶",
        "customerPNColumn": "客戶 P/N",
        "factoryPNColumn": "工廠 P/N",
        "engineerColumn": "工程師",
        "stgPNColumn": "STG P/N",
        "baseMaterialColumn": "基材",
        "solderMaskColumn": "阻焊",
        "filePathColumn": "文件路徑",
        "pluggingColumn": "塞孔類型","eqList": "EQ 清單",
        "addEQ": "添加 EQ",
        "exportExcel": "導出為 Excel",
        "searchButton": "搜尋",
        "questionLabel": "問題",
        "searching": "正在搜尋...",
        "eqInformationHeader": "EQ 資訊",
        "customerNamePlaceholder": "請輸入客戶名稱，例如：ABC Company",
        "stgPNPlaceholder": "請輸入 STG 零件號，例如：STG12345",
        "factoryEngineer": "工廠工程師",
        "factoryEngineerPlaceholder": "請輸入工廠工程師姓名，例如：張偉",
        "baseMaterialPlaceholder": "請輸入基材類型，例如：FR4",
        "customerPNPlaceholder": "請輸入客戶零件號，例如：CUST67890",
        "factoryPNPlaceholder": "請輸入工廠零件號，例如：FACT45678",
        "panelSize": "尺寸 (mm*mm)",
        "panelSizePlaceholder": "請輸入交貨板尺寸，例如：500*600 mm",
        "solderMaskPlaceholder": "請輸入阻焊層資訊，例如：綠色光澤",
        "viaPluggingType": "塞孔類型",
        "viaPluggingTypePlaceholder": "請輸入塞孔類型",
        "issueDate": "日期",
        "descriptionLabel": "描述",
        "uploadImageLabel": "上傳圖片（不支持 Gerber 文件）",
        "uploadedImageCaption": "已上傳圖片",
        "aiWriter": "AI 寫作",
        "finalDescriptionLabel": "最終描述",
        "engineerSuggestionLabel": "工程師建議",
        "attachmentLabel": "附件",
        "reviewingStatus": "審核中",
        "pendingStatus": "待處理",
        "closedStatus": "已關閉",
        "missingFieldsError": "請填寫所有必填欄位。",
        "noQuestionsError": "請至少添加一個問題。",
        "exportingAndSending": "正在導出並發送...",
        "exportReviewingSuccess": "EQ 已導出並發送！",
        "exportPendingSuccess": "待處理問題已導出！",
        "exportClosedSuccess": "客戶回覆已保存！",
        "NewQ":"新問題",
        "Setting":"设置",
    },
    "de": {"eqList": "EQ-Liste","questionPrefix": "Frage:",
        "No Description": "Keine Beschreibung",
        "unknown": "Unbekannt",
        "Create_eq_title": "Erstellen einer EQ-Schnittstelle",
        "similarityLabel": "Ähnlichkeit: {similarity}%",
        "noReply": "Keine Antwort",
        "replyImageCaption": "Antwortbild",
        "csvFileNotFound": "CSV-Datei {file} existiert nicht",
        "csvReadError": "CSV-Datei {file} kann nicht gelesen werden: {error}",
        "csvUtf8Warning": "UTF-8-Codierung fehlgeschlagen, versuche mit latin1-Codierung zu lesen {file}",
        "csvEmptyWarning": "CSV-Datei {file} ist leer",
        "imageNotFoundWarning": "Bild {image} in Zeile {row} existiert nicht in {dir}",
        "rowProcessingError": "Fehler beim Verarbeiten von Zeile {row}, Zeile übersprungen: {error}",
        "csvNoDataWarning": "CSV-Datei {file} hat keine gültigen Daten generiert",
        "csvLoadSuccess": "Erfolgreich {count} Datensätze aus {file} geladen",
        "addEQ": "EQ hinzufügen",
        "exportExcel": "Als Excel exportieren",
        "searchButton": "Suchen",
        "questionLabel": "Frage",
        "searching": "Suche läuft...",
        "eqInformationHeader": "EQ-Informationen",
        "customerNamePlaceholder": "Bitte geben Sie den Kundennamen ein, z.B.: ABC Company",
        "stgPNPlaceholder": "Bitte geben Sie die STG-Teilenummer ein, z.B.: STG12345",
        "factoryEngineer": "Fabrikingenieur",
        "factoryEngineerPlaceholder": "Bitte geben Sie den Namen des Fabrikingenieurs ein, z.B.: Zhang Wei",
        "baseMaterialPlaceholder": "Bitte geben Sie den Basismaterialtyp ein, z.B.: FR4",
        "customerPNPlaceholder": "Bitte geben Sie die Kunden-Teilenummer ein, z.B.: CUST67890",
        "factoryPNPlaceholder": "Bitte geben Sie die Fabrik-Teilenummer ein, z.B.: FACT45678",
        "panelSize": "Größe (mm*mm)",
        "panelSizePlaceholder": "Bitte geben Sie die Lieferplattengröße ein, z.B.: 500*600 mm",
        "solderMaskPlaceholder": "Bitte geben Sie die Lötstopplack-Informationen ein, z.B.: Grün glänzend",
        "viaPluggingType": "Vias-Typ",
        "viaPluggingTypePlaceholder": "Bitte geben Sie den Vias-Typ ein",
        "issueDate": "Datum",
        "descriptionLabel": "Beschreibung",
        "uploadImageLabel": "Bild hochladen (Gerber-Dateien werden nicht unterstützt)",
        "uploadedImageCaption": "Hochgeladenes Bild",
        "aiWriter": "KI-Schreiber",
        "finalDescriptionLabel": "Endgültige Beschreibung",
        "engineerSuggestionLabel": "Vorschlag des Ingenieurs",
        "attachmentLabel": "Anhang",
        "reviewingStatus": "In Überprüfung",
        "pendingStatus": "Ausstehend",
        "closedStatus": "Geschlossen",
        "missingFieldsError": "Bitte füllen Sie alle erforderlichen Felder aus.",
        "noQuestionsError": "Bitte fügen Sie mindestens eine Frage hinzu.",
        "exportingAndSending": "Exportieren und Senden läuft...",
        "exportReviewingSuccess": "EQ wurde exportiert und gesendet!",
        "exportPendingSuccess": "Ausstehende Probleme wurden exportiert!",
        "exportClosedSuccess": "Kundenantwort wurde gespeichert!",
        "searchKeyword": "Kundenname, Kunden P/N suchen...",
        "searchItemCode": "Artikelcode/STG P/N suchen...",
        "allStatus": "Alle Status",
        "allFactories": "Alle Werke",
        "engineerTeam": "Ingenieurteam",
        "engineerName": "Ingenieurname",
        "csName": "Kundendienstname",
        "noDataFound": "Keine Daten gefunden",
        "previous": "Vorherige",
        "next": "Nächste",
        "page": "Seite",
        "of": "von",
        "perPage": "pro Seite",
        "backToDashboard": "Zurück zum Dashboard",
        "selectAll": "Alle auswählen",
        "image": "Bild",
        "translateText": "Text übersetzen",
        "translateDocument": "Dokument übersetzen",
        "translateImage": "Bild übersetzen",
        "translateWeb": "Webseite übersetzen",
        "sourceLang": "Ausgangssprache",
        "targetLang": "Zielsprache",
        "swapLang": "Sprachen tauschen",
        "inputText": "Zu übersetzenden Text eingeben...",
        "uploadDocument": "Dokument hochladen (.docx, .pdf, .txt)",
        "uploadImage": "Bild hochladen (.jpg, .png)",
        "inputUrl": "Web-URL eingeben",
        "noTextExtracted": "Kein Text extrahiert",
        "translationFailed": "Übersetzung fehlgeschlagen",
        "usageInstructions": """
            **Gebrauchsanweisung:**
            - Wählen Sie die Quell- und Zielsprache (oder wählen Sie „Automatische Erkennung“ für die Quellsprache).
            - Geben Sie Text ein, laden Sie ein Dokument, ein Bild hoch oder geben Sie eine Web-URL in der entsprechenden Registerkarte ein.
            - Klicken Sie auf die entsprechende „Übersetzen“-Schaltfläche, um die Ergebnisse anzuzeigen.
            - Verwenden Sie die 🔄 Schaltfläche, um die Sprachen zu tauschen.
        """,
        "languageSelect": "Sprache wählen",
        "createNewCase": "Neuen Fall erstellen",
        "editEQ": "EQ bearbeiten",
        "exportEQ": "EQ exportieren",
        "eqInformation": "EQ-Informationen",
        "questionDescription": "Problem Beschreibung",
        "uploadImage": "Zusätzliche Bilder hochladen",
        "finalDescription": "Endgültige Beschreibung",
        "engineerSuggestion": "Vorschlag des Ingenieurs",
        "attachments": "Anhänge",
        "save": "Speichern",
        "delete": "Löschen",
        "addQuestion": "Frage hinzufügen",
        "exportAndSend": "Exportieren und senden",
        "pendingIssues": "Ausstehende Probleme",
        "statusTracking": "Statusverfolgung",
        "recentQuestions": "Neueste Fragen",
        "viewDetails": "Vollständige Details anzeigen",
        "faq_title": "Schnittstelle zur Verwaltung von EQ-Fragen",
        "eq_search_title": "EQ-Suchseite",
        "create_eq_title": "Erstellen einer EQ-Schnittstelle",
        "translator_title": "Übersetzer",
        "dashboard_title": "Hauptschnittstelle","eqOverview": "Übersicht der EQs",
        "unresolvedEQs": "Offene EQs (nach Datum sortiert)",
        "unresolvedDescription": "Offene EQs: EQs mit Status Reviewing und Pending.<br>Tage = Systemdatum - EQ-Erstellungsdatum",
        "over7Days": "Über 7 Tage",
        "between2to7Days": "2 bis 7 Tage",
        "under2Days": "Weniger als 2 Tage",
        "viewDetails": "Details anzeigen",
        "navigateToEQManage": "Zur EQ-Management-Seite navigieren, Filterbedingung: {filter}",
        "filterOver7": "Über 7 Tage",
        "filterBetween2to7": "2 bis 7 Tage",
        "filterUnder2": "Weniger als 2 Tage","filterByCustomer": "Nach Kunden filtern",
        "selectCustomer": "Kunden auswählen",
        "allCustomers": "Alle Kunden",
        "allStatuses": "Alle Status",
        "keyword": "Schlüsselwort",
        "startDate": "Startdatum",
        "endDate": "Enddatum",
        "manage_eq_title": "EQ-Dateiverwaltungsschnittstelle",
        "status": "Status",
        "stgPN": "STG P/N",
        "itemsPerPage": "Elemente pro Seite",
        "faqTime": "Zeit:",
        "faqCustomer": "Kunde:",
        "faqStatus": "Status:",
        "faqStgPN": "STG P/N:",
        "faqEngineer": "Ingenieur:",
        "faqCustomerReply": "Kundenantwort:",
        "previousPage": "Vorherige Seite",
        "nextPage": "Nächste Seite",
        "pageInfo": "Seite {current_page} von {total_pages} (insgesamt {total_items} Einträge)",
        "loadFaqError": "Fehler beim Laden der FAQ-Daten: {error}","translatorHeader": "Übersetzer",
        "tabText": "Text",
        "tabDocument": "Dokument",
        "tabImage": "Bild",
        "tabWeb": "Webseite",
        "translating": "Wird übersetzt...",
        "enterTextWarning": "Bitte geben Sie den zu übersetzenden Text ein.",
        "unsupportedFileType": "Nicht unterstütztes Dateiformat.",
        "translationResult": "Übersetzungsergebnis:",
        "extractedText": "Extrahierter Text:","searchEQHeader": "EQ suchen",
        "keywordSearch": "Schlüsselwortsuche",
        "customerName": "Kundenname",
        "invalidDateRangeError": "Das Startdatum darf nicht nach dem Enddatum liegen",
        "dateFilterError": "Fehler bei der Datumsfilterung: {error}",
        "filterError": "Filterung fehlgeschlagen: {error}",
        "eqNotFoundError": "Keine entsprechenden EQ-Daten gefunden!",
        "singleEQEditError": "Bitte wählen Sie nur einen EQ zum Bearbeiten aus.",
        "exportingEQs": "Exportiere {count} EQs...",
        "downloadCSV": "CSV herunterladen",
        "exportedEQsFile": "exported_eqs.csv",
        "selectEQExportError": "Bitte wählen Sie mindestens einen EQ zum Exportieren aus.",
        "exportSuccess": "{count} EQs wurden exportiert!",
        "selectColumn": "Auswählen",
        "idColumn": "ID",
        "eqStatusColumn": "EQ-Status",
        "closeDateColumn": "Schließungsdatum",
        "customerColumn": "Kunde",
        "customerPNColumn": "Kunden P/N",
        "factoryPNColumn": "Fabrik P/N",
        "engineerColumn": "Ingenieur",
        "stgPNColumn": "STG P/N",
        "baseMaterialColumn": "Basismaterial",
        "solderMaskColumn": "Lötstopplack",
        "filePathColumn": "Dateipfad",
        "pluggingColumn": "Vias-Typ","eqList": "EQ-Liste",
        "addEQ": "EQ hinzufügen",
        "exportExcel": "Als Excel exportieren",
        "searchButton": "Suchen",
        "questionLabel": "Frage",
        "searching": "Suche läuft...",
        "eqInformationHeader": "EQ-Informationen",
        "customerNamePlaceholder": "Bitte geben Sie den Kundennamen ein, z.B.: ABC Company",
        "stgPNPlaceholder": "Bitte geben Sie die STG-Teilenummer ein, z.B.: STG12345",
        "factoryEngineer": "Fabrikingenieur",
        "factoryEngineerPlaceholder": "Bitte geben Sie den Namen des Fabrikingenieurs ein, z.B.: Zhang Wei",
        "baseMaterialPlaceholder": "Bitte geben Sie den Basismaterialtyp ein, z.B.: FR4",
        "customerPNPlaceholder": "Bitte geben Sie die Kunden-Teilenummer ein, z.B.: CUST67890",
        "factoryPNPlaceholder": "Bitte geben Sie die Fabrik-Teilenummer ein, z.B.: FACT45678",
        "panelSize": "Größe (mm*mm)",
        "panelSizePlaceholder": "Bitte geben Sie die Lieferplattengröße ein, z.B.: 500*600 mm",
        "solderMaskPlaceholder": "Bitte geben Sie die Lötstopplack-Informationen ein, z.B.: Grün glänzend",
        "viaPluggingType": "Vias-Typ",
        "viaPluggingTypePlaceholder": "Bitte geben Sie den Vias-Typ ein",
        "issueDate": "Datum",
        "descriptionLabel": "Beschreibung",
        "uploadImageLabel": "Bild hochladen (Gerber-Dateien werden nicht unterstützt)",
        "uploadedImageCaption": "Hochgeladenes Bild",
        "aiWriter": "KI-Schreiber",
        "finalDescriptionLabel": "Endgültige Beschreibung",
        "engineerSuggestionLabel": "Vorschlag des Ingenieurs",
        "attachmentLabel": "Anhang",
        "reviewingStatus": "In Überprüfung",
        "pendingStatus": "Ausstehend",
        "closedStatus": "Geschlossen",
        "missingFieldsError": "Bitte füllen Sie alle erforderlichen Felder aus.",
        "noQuestionsError": "Bitte fügen Sie mindestens eine Frage hinzu.",
        "exportingAndSending": "Exportieren und Senden läuft...",
        "exportReviewingSuccess": "EQ wurde exportiert und gesendet!",
        "exportPendingSuccess": "Ausstehende Probleme wurden exportiert!",
        "exportClosedSuccess": "Kundenantwort wurde gespeichert!",
        "NewQ":"Neue Frage",
                "Setting":"Einstellung",
    },
    "en": {"eqList": "EQ List","questionPrefix": "Question:",
        "unknown": "Unknown",
        "manage_eq_title": "EQ File Management Page",
        "similarityLabel": "Similarity: {similarity}%",
        "noReply": "No Reply",
        "replyImageCaption": "Reply Image",
        "csvFileNotFound": "CSV file {file} does not exist",
        "csvReadError": "Unable to read CSV file {file}: {error}",
        "csvUtf8Warning": "UTF-8 encoding failed, attempting to read {file} with latin1 encoding",
        "csvEmptyWarning": "CSV file {file} is empty",
        "imageNotFoundWarning": "Image {image} in row {row} does not exist in {dir}",
        "rowProcessingError": "Error processing row {row}, skipping row: {error}",
        "csvNoDataWarning": "CSV file {file} generated no valid data",
        "csvLoadSuccess": "Successfully loaded {count} records from {file}",
        "addEQ": "Add EQ",
        "exportExcel": "Export as Excel",
        "searchButton": "Search",
        "questionLabel": "Question",
        "searching": "Searching...",
        "No Description": "No Description",
        "Setting":"Setting",
        "eqInformationHeader": "EQ Information",
        "customerNamePlaceholder": "Please enter customer name, e.g., ABC Company",
        "stgPNPlaceholder": "Please enter STG part number, e.g., STG12345",
        "factoryEngineer": "Factory Engineer",
        "factoryEngineerPlaceholder": "Please enter factory engineer name, e.g., Zhang Wei",
        "baseMaterialPlaceholder": "Please enter base material type, e.g., FR4",
        "customerPNPlaceholder": "Please enter customer part number, e.g., CUST67890",
        "factoryPNPlaceholder": "Please enter factory part number, e.g., FACT45678",
        "panelSize": "Size (mm*mm)",
        "panelSizePlaceholder": "Please enter delivery panel size, e.g., 500*600 mm",
        "solderMaskPlaceholder": "Please enter solder mask information, e.g., Glossy Green",
        "viaPluggingType": "Via Plugging Type",
        "viaPluggingTypePlaceholder": "Please enter via plugging type",
        "issueDate": "Date",
        "descriptionLabel": "Description",
        "uploadImageLabel": "Upload Image (Gerber files not supported)",
        "uploadedImageCaption": "Uploaded Image",
        "aiWriter": "AI Writer",
        "finalDescriptionLabel": "Final Description",
        "engineerSuggestionLabel": "Engineer Suggestion",
        "attachmentLabel": "Attachment",
        "reviewingStatus": "Reviewing",
        "pendingStatus": "Pending",
        "closedStatus": "Closed",
        "missingFieldsError": "Please fill in all required fields.",
        "noQuestionsError": "Please add at least one question.",
        "exportingAndSending": "Exporting and sending...",
        "exportReviewingSuccess": "EQ exported and sent!",
        "exportPendingSuccess": "Pending issues exported!",
        "exportClosedSuccess": "Customer reply saved!",
        "searchKeyword": "Search Customer Name, Customer P/N...",
        "searchItemCode": "Search Item Code/STG P/N...",
        "allStatus": "All Status",
        "allFactories": "All Factories",
        "engineerTeam": "Engineer Team",
        "engineerName": "Engineer Name",
        "csName": "CS Name",
        "noDataFound": "No data found",
        "previous": "Previous",
        "next": "Next",
        "page": "Page",
        "of": "of",
        "perPage": "per page",
        "backToDashboard": "Back to Dashboard",
        "selectAll": "Select All",
        "image": "Image",
        "Create_eq_title": "EQ Creation Page",
        "translateText": "Translate Text",
        "translateDocument": "Translate Document",
        "translateImage": "Translate Image",
        "translateWeb": "Translate Web",
        "sourceLang": "Source Language",
        "targetLang": "Target Language",
        "swapLang": "Swap Languages",
        "inputText": "Input text to translate...",
        "uploadDocument": "Upload document (.docx, .pdf, .txt)",
        "uploadImage": "Upload image (.jpg, .png)",
        "inputUrl": "Input web URL",
        "noTextExtracted": "No text extracted",
        "translationFailed": "Translation failed",
        "usageInstructions": """
            **Usage Instructions:**
            - Select source and target languages (or choose "Auto Detect" for source).
            - Enter text, upload a document, upload an image, or input a web URL in the respective tab.
            - Click the corresponding "Translate" button to view results.
            - Use the 🔄 button to swap languages.
        """,
        "languageSelect": "Select Language",
        "createNewCase": "Create New Case",
        "editEQ": "Edit EQ",
        "exportEQ": "Export EQ",
        "eqInformation": "EQ Information",
        "questionDescription": "Question Description",
        "uploadImage": "Upload Related Images",
        "finalDescription": "Final Description",
        "engineerSuggestion": "Engineer Suggestion",
        "attachments": "Attachments",
        "save": "Save",
        "delete": "Delete",
        "addQuestion": "Add Question",
        "exportAndSend": "Export and Send",
        "pendingIssues": "Pending Issues",
        "statusTracking": "Status Tracking",
        "recentQuestions": "Recent Questions",
        "viewDetails": "View Full Details",
        "faq_title": "EQ Question Manager",
        "eq_search_title": "EQ Searching Page",
        "create_eq_title": "EQ Creation Page",
        "translator_title": "Translator",
        "dashboard_title": "EQ Management Dashboard","eqOverview": "EQs Overview",
        "unresolvedEQs": "Unresolved EQs (by Date)",
        "unresolvedDescription": "Unresolved EQs: EQs with status Reviewing and Pending.<br>Days = System Date - EQ Creation Date",
        "over7Days": "Over 7 Days",
        "between2to7Days": "2 to 7 Days",
        "under2Days": "Under 2 Days",
        "viewDetails": "View Details",
        "navigateToEQManage": "Navigated to EQ Management page, filter: {filter}",
        "filterOver7": "Over 7 Days",
        "filterBetween2to7": "2 to 7 Days",
        "filterUnder2": "Under 2 Days","filterByCustomer": "Filter by Customer",
        "selectCustomer": "Select Customer",
        "allCustomers": "All Customers",
        "allStatuses": "All Statuses",
        "keyword": "Keyword",
        "startDate": "Start Date",
        "endDate": "End Date",
        "status": "Status",
        "stgPN": "STG P/N",
        "itemsPerPage": "Items per Page",
        "faqTime": "Time:",
        "faqCustomer": "Customer:",
        "faqStatus": "Status:",
        "faqStgPN": "STG P/N:",
        "faqEngineer": "Engineer:",
        "faqCustomerReply": "Customer Reply:",
        "previousPage": "Previous Page",
        "nextPage": "Next Page",
        "pageInfo": "Page {current_page} of {total_pages} (Total {total_items} items)",
        "loadFaqError": "Failed to load FAQ data: {error}","translatorHeader": "Translator",
        "tabText": "Text",
        "tabDocument": "Document",
        "tabImage": "Image",
        "tabWeb": "Web",
        "translating": "Translating...",
        "enterTextWarning": "Please enter the text to translate.",
        "unsupportedFileType": "Unsupported file type.",
        "translationResult": "Translation Result:",
        "extractedText": "Extracted Text:","searchEQHeader": "Search EQ",
        "keywordSearch": "Keyword Search",
        "customerName": "Customer Name",
        "invalidDateRangeError": "Start date cannot be later than end date",
        "dateFilterError": "Date filtering error: {error}",
        "filterError": "Filtering failed: {error}",
        "eqNotFoundError": "No corresponding EQ data found!",
        "singleEQEditError": "Please select only one EQ to edit.",
        "exportingEQs": "Exporting {count} EQs...",
        "downloadCSV": "Download CSV",
        "exportedEQsFile": "exported_eqs.csv",
        "selectEQExportError": "Please select at least one EQ to export.",
        "exportSuccess": "{count} EQs exported successfully!",
        "selectColumn": "Select",
        "idColumn": "ID",
        "eqStatusColumn": "EQ Status",
        "closeDateColumn": "Close Date",
        "customerColumn": "Customer",
        "customerPNColumn": "Customer P/N",
        "factoryPNColumn": "Factory P/N",
        "engineerColumn": "Engineer",
        "stgPNColumn": "STG P/N",
        "baseMaterialColumn": "Base Material",
        "solderMaskColumn": "Solder Mask",
        "filePathColumn": "File Path",
        "pluggingColumn": "Plugging Type","eqList": "EQ List",
        "addEQ": "Add EQ",
        "exportExcel": "Export as Excel",
        "searchButton": "Search",
        "questionLabel": "Question",
        "searching": "Searching...",
        "NewQ":"New Question",
        "eqInformationHeader": "EQ Information",
        "customerNamePlaceholder": "Please enter customer name, e.g., ABC Company",
        "stgPNPlaceholder": "Please enter STG part number, e.g., STG12345",
        "factoryEngineer": "Factory Engineer",
        "factoryEngineerPlaceholder": "Please enter factory engineer name, e.g., Zhang Wei",
        "baseMaterialPlaceholder": "Please enter base material type, e.g., FR4",
        "customerPNPlaceholder": "Please enter customer part number, e.g., CUST67890",
        "factoryPNPlaceholder": "Please enter factory part number, e.g., FACT45678",
        "panelSize": "Size (mm*mm)",
        "panelSizePlaceholder": "Please enter delivery panel size, e.g., 500*600 mm",
        "solderMaskPlaceholder": "Please enter solder mask information, e.g., Glossy Green",
        "viaPluggingType": "Via Plugging Type",
        "viaPluggingTypePlaceholder": "Please enter via plugging type",
        "issueDate": "Date",
        "descriptionLabel": "Description",
        "uploadImageLabel": "Upload Image (Gerber files not supported)",
        "uploadedImageCaption": "Uploaded Image",
        "aiWriter": "AI Writer",
        "finalDescriptionLabel": "Final Description",
        "engineerSuggestionLabel": "Engineer Suggestion",
        "attachmentLabel": "Attachment",
        "reviewingStatus": "Reviewing",
        "pendingStatus": "Pending",
        "closedStatus": "Closed",
        "missingFieldsError": "Please fill in all required fields.",
        "noQuestionsError": "Please add at least one question.",
        "exportingAndSending": "Exporting and sending...",
        "exportReviewingSuccess": "EQ exported and sent!",
        "exportPendingSuccess": "Pending issues exported!",
        "exportClosedSuccess": "Customer reply saved!"
    }
}

# 日期格式
DATE_FORMAT = "%Y-%m-%d"

# 翻译相关配置
TRANSLATOR_CONFIG = {
    "languages": ["Auto Detect", "English", "Chinese (Simplified)", "German", "French", "Japanese"],
    "file_types": ["docx", "pdf", "txt", "jpg", "png"]
}


current_file = Path(__file__).resolve()
project_root = current_file.parent

# 构建图片目录路径
image_dir = project_root / "Data" / "images"
database_dir = project_root / "Data" / "Dataset.csv"
model_dir = project_root / "Data" / "Model"
EQ_excel_dir = project_root / "Data" / "EQ Excel"

source_path = {'database':database_dir,
                'images':image_dir,
                'model':model_dir,
                'EQ excel':EQ_excel_dir,
                'embedding': 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
                'search': {
                            'default_k': 20,
                            'similarity_threshold': 0.7,
    }}
