DASHBOARD_MESSAGES = {
    "zh-CN": {
        "pendingEQs": "待解决问题",
        "statusTracking": "问题状态追踪",
        "recentQuestions": "最新问题展示",
        "viewDetails": "查看完整详情",
        "detail": "详情"
    },
    "zh-TW": {
        "pendingEQs": "待解決問題",
        "statusTracking": "問題狀態追蹤",
        "recentQuestions": "最新問題展示",
        "viewDetails": "查看完整詳情",
        "detail": "詳情"
    },
    "de": {
        "pendingEQs": "Offene EQs",
        "statusTracking": "EQ-Statusverfolgung",
        "recentQuestions": "Neueste Fragen",
        "viewDetails": "Details anzeigen",
        "detail": "Details"
    },
    "en": {
        "pendingEQs": "Pending EQs",
        "statusTracking": "EQs Status Tracking",
        "recentQuestions": "Recent Questions",
        "viewDetails": "View Full Details",
        "detail": "Detail"
    }
}


FAQ_MESSAGES = {
    "zh-CN": {
        "faq_title": "常见问题解答",
        "selectCustomer": "选择客户",
        "filterKeyword": "关键词",
        "filterStartDate": "开始日期",
        "filterEndDate": "结束日期",
        "filterStatus": "状态",
        "filterSTGPN": "STG P/N",
        "allCustomers": "所有客户",
        "allStatuses": "所有状态",
        "noDataFound": "没有符合条件的问题。",
        "prevPage": "上一页",
        "nextPage": "下一页",
        "pageInfo": "第 {current} 页 / 共 {total} 页（总计 {count} 条）",
        "customerResponse": "客户回复",
        "questionTime": "时间",
        "questionCustomer": "客户",
        "questionStatus": "状态",
        "questionSTG": "STG P/N",
        "questionEngineer": "工程师",
        "itemsPerPage": "每页显示条数"
    },
    "zh-TW": {
        "faq_title": "常見問題解答",
        "selectCustomer": "選擇客戶",
        "filterKeyword": "關鍵詞",
        "filterStartDate": "開始日期",
        "filterEndDate": "結束日期",
        "filterStatus": "狀態",
        "filterSTGPN": "STG P/N",
        "allCustomers": "所有客戶",
        "allStatuses": "所有狀態",
        "noDataFound": "沒有符合條件的問題。",
        "prevPage": "上一頁",
        "nextPage": "下一頁",
        "pageInfo": "第 {current} 頁 / 共 {total} 頁（總計 {count} 條）",
        "customerResponse": "客戶回覆",
        "questionTime": "時間",
        "questionCustomer": "客戶",
        "questionStatus": "狀態",
        "questionSTG": "STG P/N",
        "questionEngineer": "工程師",
        "itemsPerPage": "每頁顯示筆數"
    },
    "de": {
        "faq_title": "Häufig gestellte Fragen",
        "selectCustomer": "Kunden auswählen",
        "filterKeyword": "Stichwort",
        "filterStartDate": "Startdatum",
        "filterEndDate": "Enddatum",
        "filterStatus": "Status",
        "filterSTGPN": "STG P/N",
        "allCustomers": "Alle Kunden",
        "allStatuses": "Alle Status",
        "noDataFound": "Keine passenden Fragen gefunden.",
        "prevPage": "Vorherige Seite",
        "nextPage": "Nächste Seite",
        "pageInfo": "Seite {current} / {total} (Insgesamt {count})",
        "customerResponse": "Kundenantwort",
        "questionTime": "Datum",
        "questionCustomer": "Kunde",
        "questionStatus": "Status",
        "questionSTG": "STG P/N",
        "questionEngineer": "Ingenieur",
        "itemsPerPage": "Einträge pro Seite"
    },
    "en": {
        "faq_title": "Frequently Asked Questions",
        "selectCustomer": "Select Customer",
        "filterKeyword": "Keyword",
        "filterStartDate": "Start Date",
        "filterEndDate": "End Date",
        "filterStatus": "Status",
        "filterSTGPN": "STG P/N",
        "allCustomers": "All Customers",
        "allStatuses": "All Statuses",
        "noDataFound": "No matching questions found.",
        "prevPage": "Previous",
        "nextPage": "Next",
        "pageInfo": "Page {current} of {total} (Total {count} entries)",
        "customerResponse": "Customer Response",
        "questionTime": "Time",
        "questionCustomer": "Customer",
        "questionStatus": "Status",
        "questionSTG": "STG P/N",
        "questionEngineer": "Engineer",
        "itemsPerPage": "Items per page"
    }
}


TRANSLATOR_MESSAGES = {
    "zh-CN": {
        "title": "翻译器",
        "textTab": "文本",
        "documentTab": "文档",
        "imageTab": "图片",
        "webTab": "网页",
        "inputText": "输入要翻译的文本...",
        "translateText": "翻译文本",
        "uploadDocument": "上传文档（.docx、.pdf、.txt）",
        "translateDocument": "翻译文档",
        "uploadImage": "上传图片（.jpg、.png）",
        "translateImage": "翻译图片",
        "inputUrl": "输入网页 URL",
        "translateWeb": "翻译网页",
        "extractedText": "提取的文本:",
        "translationResult": "翻译结果:",
        "translationFailed": "翻译失败",
        "noTextExtracted": "未提取到文本",
        "usageInstructions": """
            **使用说明：**
            - 选择源语言和目标语言（或选择“自动检测”源语言）。
            - 在相应标签页中输入文本、上传文档、上传图片或输入网页 URL。
            - 点击相应的“翻译”按钮查看翻译结果。
        """
    },
    "zh-TW": {
        "title": "翻譯器",
        "textTab": "文本",
        "documentTab": "文件",
        "imageTab": "圖片",
        "webTab": "網頁",
        "inputText": "輸入要翻譯的文本...",
        "translateText": "翻譯文本",
        "uploadDocument": "上傳文件（.docx、.pdf、.txt）",
        "translateDocument": "翻譯文件",
        "uploadImage": "上傳圖片（.jpg、.png）",
        "translateImage": "翻譯圖片",
        "inputUrl": "輸入網頁 URL",
        "translateWeb": "翻譯網頁",
        "extractedText": "提取的文本:",
        "translationResult": "翻譯結果:",
        "translationFailed": "翻譯失敗",
        "noTextExtracted": "未提取到文本",
        "usageInstructions": """
            **使用說明：**
            - 選擇源語言和目標語言（或選擇“自動檢測”源語言）。
            - 在相應標籤頁中輸入文本、上傳文件、上傳圖片或輸入網頁 URL。
            - 點擊相應的“翻譯”按鈕查看翻譯結果。
        """
    },
    "de": {
        "title": "Übersetzer",
        "textTab": "Text",
        "documentTab": "Dokument",
        "imageTab": "Bild",
        "webTab": "Webseite",
        "inputText": "Text zum Übersetzen eingeben...",
        "translateText": "Text übersetzen",
        "uploadDocument": "Dokument hochladen (.docx, .pdf, .txt)",
        "translateDocument": "Dokument übersetzen",
        "uploadImage": "Bild hochladen (.jpg, .png)",
        "translateImage": "Bild übersetzen",
        "inputUrl": "Web-URL eingeben",
        "translateWeb": "Webseite übersetzen",
        "extractedText": "Extrahierter Text:",
        "translationResult": "Übersetzungsergebnis:",
        "translationFailed": "Übersetzung fehlgeschlagen",
        "noTextExtracted": "Kein Text extrahiert",
        "usageInstructions": """
            **Anleitung:**
            - Wählen Sie Quell- und Zielsprache (oder verwenden Sie „Automatisch erkennen“).
            - Geben Sie Text ein, laden Sie Dokumente oder Bilder hoch oder fügen Sie eine Web-URL ein.
            - Klicken Sie auf „Übersetzen“, um das Ergebnis anzuzeigen.
        """
    },
    "en": {
        "title": "Translator",
        "textTab": "Text",
        "documentTab": "Document",
        "imageTab": "Image",
        "webTab": "Web",
        "inputText": "Input text to translate...",
        "translateText": "Translate Text",
        "uploadDocument": "Upload document (.docx, .pdf, .txt)",
        "translateDocument": "Translate Document",
        "uploadImage": "Upload image (.jpg, .png)",
        "translateImage": "Translate Image",
        "inputUrl": "Input web URL",
        "translateWeb": "Translate Web",
        "extractedText": "Extracted Text:",
        "translationResult": "Translation Result:",
        "translationFailed": "Translation failed",
        "noTextExtracted": "No text extracted",
        "usageInstructions": """
            **Usage Instructions:**
            - Select source and target languages (or use Auto Detect).
            - Input text, upload a document or image, or provide a webpage URL.
            - Click the translate button to view the results.
        """
    }
}


CREATE_MESSAGES = {
    "zh-CN": {
        "eqInformation": "EQ 信息",
        "customerName": "客户名称",
        "customerPN": "客户 P/N",
        "stgPN": "STG P/N",
        "factoryPN": "工厂 P/N",
        "factoryEngineer": "工厂工程师",
        "baseMaterial": "基材",
        "issueDate": "日期",
        "panelSize": "交货板尺寸 (mm*mm)",
        "solderMask": "阻焊层",
        "status": "状态",
        "viaPluggingType": "塞孔类型",
        "questionTitle": "问题",
        "questionDesc": "问题描述",
        "finalDescription": "最终描述",
        "search": "搜索",
        "engineerSuggestion": "工程师建议",
        "attachments": "附件",
        "save": "保存",
        "delete": "删除",
        "addQuestion": "添加问题",
        "exportAndSend": "导出并发送",
        "errorMissingFields": "请填写所有必填字段。",
        "errorNoQuestion": "请至少添加一个问题。",
        "successExported": "EQ 已导出并发送！",
        "successPending": "待处理问题已导出！",
        "successClosed": "客户回复已保存！",
        "uploadImage": "上传相关图片 (请注意Gerber File不可使用)",
        "uploadedImage": "已上传图片"
    },
    "zh-TW": {
        "eqInformation": "EQ 資訊",
        "customerName": "客戶名稱",
        "customerPN": "客戶 P/N",
        "stgPN": "STG P/N",
        "factoryPN": "工廠 P/N",
        "factoryEngineer": "工廠工程師",
        "baseMaterial": "基材",
        "issueDate": "日期",
        "panelSize": "交貨板尺寸 (mm*mm)",
        "solderMask": "阻焊層",
        "status": "狀態",
        "viaPluggingType": "塞孔類型",
        "questionTitle": "問題",
        "questionDesc": "問題描述",
        "finalDescription": "最終描述",
        "search": "搜尋",
        "engineerSuggestion": "工程師建議",
        "attachments": "附件",
        "save": "儲存",
        "delete": "刪除",
        "addQuestion": "新增問題",
        "exportAndSend": "匯出並發送",
        "errorMissingFields": "請填寫所有必填欄位。",
        "errorNoQuestion": "請至少新增一個問題。",
        "successExported": "EQ 已匯出並發送！",
        "successPending": "待處理問題已匯出！",
        "successClosed": "客戶回覆已儲存！",
        "uploadImage": "上傳相關圖片 (請注意 Gerber File 不可使用)",
        "uploadedImage": "已上傳圖片"
    },
    "de": {
        "eqInformation": "EQ-Informationen",
        "customerName": "Kundenname",
        "customerPN": "Kunden P/N",
        "stgPN": "STG P/N",
        "factoryPN": "Fabrik P/N",
        "factoryEngineer": "Fabrikingenieur",
        "baseMaterial": "Basismaterial",
        "issueDate": "Datum",
        "panelSize": "Plattengröße (mm*mm)",
        "solderMask": "Lötstoppmaske",
        "status": "Status",
        "viaPluggingType": "Via-Typ",
        "questionTitle": "Frage",
        "questionDesc": "Fragebeschreibung",
        "finalDescription": "Endgültige Beschreibung",
        "search": "Suchen",
        "engineerSuggestion": "Vorschlag des Ingenieurs",
        "attachments": "Anhänge",
        "save": "Speichern",
        "delete": "Löschen",
        "addQuestion": "Frage hinzufügen",
        "exportAndSend": "Exportieren und senden",
        "errorMissingFields": "Bitte füllen Sie alle erforderlichen Felder aus.",
        "errorNoQuestion": "Bitte fügen Sie mindestens eine Frage hinzu.",
        "successExported": "EQ erfolgreich exportiert und gesendet!",
        "successPending": "Offene Fragen wurden exportiert!",
        "successClosed": "Antwort vom Kunden gespeichert!",
        "uploadImage": "Relevante Bilder hochladen (Gerber-Dateien nicht erlaubt)",
        "uploadedImage": "Hochgeladenes Bild"
    },
    "en": {
        "eqInformation": "EQ Information",
        "customerName": "Customer Name",
        "customerPN": "Customer P/N",
        "stgPN": "STG P/N",
        "factoryPN": "Factory P/N",
        "factoryEngineer": "Factory Engineer",
        "baseMaterial": "Base Material",
        "issueDate": "Issue Date",
        "panelSize": "Panel Size (mm*mm)",
        "solderMask": "Solder Mask",
        "status": "Status",
        "viaPluggingType": "Via Plugging Type",
        "questionTitle": "Question",
        "questionDesc": "Question Description",
        "finalDescription": "Final Description",
        "search": "Search",
        "engineerSuggestion": "Engineer Suggestion",
        "attachments": "Attachments",
        "save": "Save",
        "delete": "Delete",
        "addQuestion": "Add Question",
        "exportAndSend": "Export and Send",
        "errorMissingFields": "Please fill out all required fields.",
        "errorNoQuestion": "Please add at least one question.",
        "successExported": "EQ exported and sent!",
        "successPending": "Pending issues exported!",
        "successClosed": "Customer reply saved!",
        "uploadImage": "Upload related image (Gerber Files not supported)",
        "uploadedImage": "Uploaded Image"
    }
}


MANAGE_MESSAGES = {
    "zh-CN": {
        "selectAll": "全选",
        "createNew": "创建新案例",
        "editEQ": "编辑 EQ",
        "exportEQ": "导出 EQ",
        "noDataFound": "未找到匹配的数据",
        "page": "第",
        "prevPage": "上一页",
        "nextPage": "下一页",
        "searchEQ": "搜索 EQ",
        "engineerName": "工程师",
        "allStatus": "所有状态",
        "startAfterEnd": "开始日期不能晚于结束日期",
        "dateFilterError": "日期筛选错误",
        "filterFailed": "筛选失败",
        "notFound": "未找到对应 EQ 数据！",
        "onlySelectOne": "请仅选择一个 EQ 进行编辑。",
        "backToDashboard": "返回仪表板"
    },
    "zh-TW": {
        "selectAll": "全選",
        "createNew": "建立新案例",
        "editEQ": "編輯 EQ",
        "exportEQ": "匯出 EQ",
        "noDataFound": "未找到符合的資料",
        "page": "第",
        "prevPage": "上一頁",
        "nextPage": "下一頁",
        "searchEQ": "搜尋 EQ",
        "engineerName": "工程師",
        "allStatus": "所有狀態",
        "startAfterEnd": "開始日期不能晚於結束日期",
        "dateFilterError": "日期篩選錯誤",
        "filterFailed": "篩選失敗",
        "notFound": "未找到對應 EQ 資料！",
        "onlySelectOne": "請僅選擇一個 EQ 進行編輯。",
        "backToDashboard": "返回儀表板"
    },
    "de": {
        "selectAll": "Alle auswählen",
        "createNew": "Neuen Fall erstellen",
        "editEQ": "EQ bearbeiten",
        "exportEQ": "EQ exportieren",
        "noDataFound": "Keine passenden Daten gefunden",
        "page": "Seite",
        "prevPage": "Vorherige Seite",
        "nextPage": "Nächste Seite",
        "searchEQ": "EQ suchen",
        "engineerName": "Ingenieur",
        "allStatus": "Alle Status",
        "startAfterEnd": "Startdatum darf nicht nach dem Enddatum liegen",
        "dateFilterError": "Datumsfilterfehler",
        "filterFailed": "Filterung fehlgeschlagen",
        "notFound": "Keine entsprechende EQ-Daten gefunden!",
        "onlySelectOne": "Bitte nur einen EQ zur Bearbeitung auswählen.",
        "backToDashboard": "Zurück zum Dashboard"
    },
    "en": {
        "selectAll": "Select All",
        "createNew": "Create New Case",
        "editEQ": "Edit EQ",
        "exportEQ": "Export EQ",
        "noDataFound": "No matching data found",
        "page": "Page",
        "prevPage": "Previous Page",
        "nextPage": "Next Page",
        "searchEQ": "Search EQ",
        "engineerName": "Engineer",
        "allStatus": "All Statuses",
        "startAfterEnd": "Start date cannot be after end date",
        "dateFilterError": "Date filter error",
        "filterFailed": "Filtering failed",
        "notFound": "EQ data not found!",
        "onlySelectOne": "Please select only one EQ to edit.",
        "backToDashboard": "Back to Dashboard"
    }
}